; -*- lexical-binding: t -*-

; x-release-please-start-version
(package "repeatable" "0.2.6" "Repeatable prefix commands with which-key")
; x-release-please-end
(website-url "https://github.com/chiply/repeatable")
(keywords "convenience" "keys")
(package-file "repeatable.el")
(files "repeatable.el")
(script "test" "eask test ert test/repeatable-test.el")
(source "gnu")
(source "melpa")
(depends-on "emacs" "30.1")
(development
 (depends-on "package-lint")
 (depends-on "elisp-lint")
 (depends-on "relint"))
