; -*- lexical-binding: t -*-

; x-release-please-start-version
(package "repeatable-lite" "0.1.1" "Repeatable prefix commands with which-key")
; x-release-please-end
(website-url "https://github.com/chiply/repeatable-lite")
(keywords "convenience" "keys")
(package-file "repeatable-lite.el")
(files "repeatable-lite.el")
(script "test" "echo \"No tests yet\"")
(source "gnu")
(source "melpa")
(depends-on "emacs" "29.1")
(depends-on "which-key" "3.5.0")
(development (depends-on "package-lint"))
